"""Health / GPU / engine availability endpoint."""

from __future__ import annotations

import platform
import shutil

from fastapi import APIRouter

from app.config import COMFYUI_URL, DEEPSEEK_API_KEY, PHASE1_DIR
from app.schemas import EngineHealth, HealthResponse
from app.services import generative_service

router = APIRouter(prefix="/api/v1/health", tags=["health"])


def _phase1_env_ok() -> bool:
    """Program-video pipeline needs node + render_video.mjs + (for real runs) DeepSeek."""
    return bool(shutil.which("node")) and (PHASE1_DIR / "tools" / "render_video.mjs").is_file()


@router.get("", response_model=HealthResponse)
def health() -> HealthResponse:
    gen = generative_service.probe()
    deepseek_ok = bool(DEEPSEEK_API_KEY)
    phase1_ok = _phase1_env_ok()
    return HealthResponse(
        status="ok",
        python=platform.python_version(),
        gpu=gen,
        engines={
            "auto": EngineHealth(
                available=deepseek_ok and phase1_ok,
                detail=f"DeepSeek={'configured' if deepseek_ok else 'missing'} · render env={'OK' if phase1_ok else 'missing node/tools'}",
            ),
            "deterministic": EngineHealth(
                available=deepseek_ok and phase1_ok,
                detail="same as auto (program video generated by Phase 1)",
            ),
            "generative": EngineHealth(
                available=gen["available"],
                detail=f"local ComfyUI {COMFYUI_URL} · {gen['detail']}",
            ),
        },
    )
